sudo: required
language: node_js
node_js:
  - "8.12.0"
services:
  - docker

before_install:
  - docker build -t huy/docker-react -f Dockerfile.dev .

script:
  - docker run huy/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-673499634820"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
